version: '3'
services:
  blog:
    build: ./blog
    container_name: blog_c
    ports:
      - '3000:3000'
    stdin_open: true
    volumes:
      - ./blog:/app
      - ./app/node_modules
  api:
    build: ./api
    container_name: api_c
    ports:
      - '9000:9000'
    volumes:
      - ./api:/app
      - ./app/node_modules
  nginx:
    build: ./nginx
    container_name: nginx_c
    ports:
      - '8080:80'
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
