version: '3'
services:
  blog:
    build: ./blog
    container_name: blog_c
    stdin_open: true
  api:
    build: ./api
    container_name: api_c
  nginx:
    build: ./nginx
    container_name: nginx_c
    ports:
      - '8080:80'
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
