import type { GetServerSidePropsContext, InferGetServerSidePropsType } from 'next'
import Head from 'next/head'

export async function getServerSideProps(context: GetServerSidePropsContext) {
  const { id } = context.params || {};

  /* host.docker.internal = localhost */
  const res = await fetch(`http://host.docker.internal:8080/api/post/${id}`);
  const data = await res.json() as Post;

  return { props: { data } };
}

const Post = ({ data }: InferGetServerSidePropsType<typeof getServerSideProps>) => {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <h1>
          {`Post Title: ${data.title}`}
        </h1>
      </main>
    </div>
  )
}

export default Post
